config/routes.rb
Rails.application.routes.draw do
  get 'blog/index'
	devise_for :users
  get 'tweets/index'
  
  root to: "plans#index"

	resources :plans, only: :index
	resources :rooms, only: [:index, :new, :create, :destroy] do
		resources :tweets, only: [:index, :create]
	end
	resources :faces, only: [:index, :new, :create, :show]
	resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/birthplace.rb
class Birthplace < ActiveHash::Base
	self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

	include ActiveHash::Associations
  has_many :faces
	
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/department.rb
class Department < ActiveHash::Base
	self.data = [
		{ id: 1, name: '---' },
		{ id: 2, name: '総務部' },
		{ id: 3, name: '人事部' },
		{ id: 4, name: '経理部' },
		{ id: 5, name: '営業部' },
		{ id: 6, name: '開発部' },
		{ id: 7, name: '事業部' },
		{ id: 8, name: '製造部' },
		{ id: 9, name: 'その他' }
	]

	include ActiveHash::Associations
  has_many :faces

end

app/models/face.rb
class Face < ApplicationRecord
	extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :department
  belongs_to :gender
  belongs_to :birthplace
  belongs_to :history

  belongs_to :user
	has_one_attached :image

  with_options presence: true do
    validates :image
    validates :text
    validates :skill
		validates :hobby
		with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
      validates :department_id
      validates :gender_id
      validates :birthplace_id
      validates :history_id
    end
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
	self.data = [
		{ id: 1, name: '---' },
		{ id: 2, name: '女' },
		{ id: 3, name: '男' },
		{ id: 4, name: 'その他' }
	]

	include ActiveHash::Associations
  has_many :faces

end

app/models/history.rb
class History < ActiveHash::Base
	self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '１〜５年' },
    { id: 3, name: '６〜10年' },
    { id: 4, name: '11〜15年' },
    { id: 5, name: '16〜20年' },
		{ id: 6, name: '21〜25年' },
		{ id: 7, name: '26〜30年' },
		{ id: 8, name: '31年〜' }
  ]

	include ActiveHash::Associations
  has_many :faces
	
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users, validate: false
  has_many :tweets, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/.freeze }
    validates :company_number, format: { with: /\A[0-9]{8}+\z/.freeze }
  end
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :tweets
  has_many :faces
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company_number])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    @blog = Blog.new
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: '削除しました'
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
  def index
		@faces = Face.order("created_at DESC")
  end

	def new
		@face = Face.new
	end

	def create
		@face = Face.new(face_params)
    if @face.save
      redirect_to faces_path
    else
      render :new
    end
	end

	def show
		@face = Face.find(params[:id])
	end

	private

	def face_params
		params.require(:face).permit(:image, :text, :skill, :hobby, :gender_id, :birthplace_id, :department_id, :history_id).merge(user_id: current_user.id)
	end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @room = Room.find(params[:room_id])
    @tweets = @room.tweets.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @tweet = @room.tweets.new(tweet_params)
    if @tweet.save
      redirect_to room_tweets_path(@room)
    else
      @tweets = @room.tweets.includes(:user)
      render :index
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/faces_helper.rb
module FacesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/blogs/edit.html.erb
<div class="edit">
	<%= form_with(model: @blog, local: true) do |form| %>
	<h1 class="top">カレンダー（編集）</h1>
	<br>

		<div class="title">
			<div class="form-tag">タイトル</div>
			<%= form.text_field :title %>
		</div>


		<div class="content">
			<div class="form-tag">内容</div>
			<%= form.text_field :content %>
		</div>

			<div class="time">
			<div class="form-tag">時間</div>
			<%= form.datetime_select :start_time %>
		</div>


		<div class="submit">
			<%= form.submit %>
		</div>

	<% end %>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="toppage">
	<h1 class="top">カレンダー（一覧）</h1>
	<br>

	<div class="row">
		<div class="col-md-4">
			<div class="schedule">＜今後の予定＞</div>
			<table class="table">
				<tbody>
					<% @blogs.each do |blog| %>
						<tr>
							<td><%= link_to blog.title , blog %></td>
							<td><%= blog.start_time.strftime("%m月%d日") %></td>
						</tr>
					<% end %>
				</tbody>
			</table><br>


			<div class="schedule">＜予定の入力＞</div>
			<div class="schedule-contents">
				<%= form_with(model: @blog, local: true) do |form| %>

					<div class="title">
						<div class="form-tag">タイトル</div>
						<%= form.text_field :title %>
					</div>

					<div class="content">
						<div class="form-tag">内容</div>
						<%= form.text_field :content %>
					</div>

					<div class="time">
						<div class="form-tag">日時（年/月/日/時間）</div>
						<%= form.datetime_select :start_time %>
					</div>

					<div class="submit">
						<%= form.submit %>
					</div>
				<% end %>
			</div>
		</div>

		<br>


		<br>
		<div class="col-md-8">
			<%= month_calendar events: @blogs do |date, blogs| %>
				<%= date.day %>

				<% blogs.each do |blog| %>
					<div>
						<%= link_to blog.title, blog %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
	<h1 class="top">カレンダー（詳細）</h1>
	<br>
	<p>
		<div class="title">
			<strong>＜タイトル＞</strong><br>
			<%= @blog.title %>
		</div>
	</p>

	<p>
		<div class="content">
			<strong>＜内容＞</strong><br>
			<%= @blog.content %>
		</div>
	</p>

	<p>
		<div class="time">
			<strong>＜日時＞</strong><br>
			<%= @blog.start_time.strftime("%m月%d日") %>
		</div>
	</p>

	<%= link_to '編集', edit_blog_path(@blog) %>
	<%= link_to '消去',blog_path(@blog.id), method: :delete, data: { confirm: '本当に?' } %>
	<%= link_to '戻る', blogs_path %>
</div>

app/views/faces/index.html.erb
<h1 class="title-kao">カオで選ぶ</h1>
<%= link_to "カオを追加する", new_face_path, class:"post" %>

<% @faces.each do |face| %>
  <div class="face">
    <div class="face-text">
      <%= face.text %>
    </div>
    <div class="face-skill">
      <%= face.skill %>
    </div>
    <div class="face-hobby">
      <%= face.hobby %>
    </div>
  </div>
<% end %>

<div class="main-wrapper">
	<div class="icon-face">
		<img src="https://2.bp.blogspot.com/-mAPlMWTEu6w/Vf-avVV_qWI/AAAAAAAAyKQ/fFlCoLI8v0g/s800/icon_business_woman06.png" width="220px" height="200px" >
		<p>名前１</p>
	</div>
	<div class="icon-face">
		<img src="https://1.bp.blogspot.com/-udC855w95dQ/Vf-an9DwChI/AAAAAAAAyIE/jJQs8BwMiSc/s800/icon_business_man05.png" width="220px" height="200px" >
		<p>名前２</p>
	</div>
	<div class="icon-face">
		<img src="https://1.bp.blogspot.com/-R5IBoqtlmUg/Vf-axcCuclI/AAAAAAAAyKw/S-DC6B55P5M/s800/icon_business_woman10.png" width="220px" height="200px" >
		<p>名前３</p>
	</div>
	<div class="icon-face">
		<img src="https://3.bp.blogspot.com/-B-xk9ZeFe4A/Vf-amDqeQmI/AAAAAAAAyHw/8oOgEX6foYc/s800/icon_business_man02.png" width="220px" height="200px" >
		<p>名前４</p>
	</div>
	<div class="icon-face">
		<img src="https://3.bp.blogspot.com/-iOrdJELd9yc/Vf-atQQbXTI/AAAAAAAAyJo/xD5HYRbATGA/s800/icon_business_woman01.png" width="220px" height="200px" >
		<p>名前５</p>
	</div>
	<div class="icon-face">
		<img src="https://4.bp.blogspot.com/-k7qQRYy2yJg/Vf-atj1jJCI/AAAAAAAAyJs/rFD5lyAn7NI/s800/icon_business_woman02.png" width="220px" height="200px" >
		<p>名前６</p>
	</div>
	<div class="icon-face">
		<img src="https://4.bp.blogspot.com/-IghrJ53dHi4/Vf-arG5MJ4I/AAAAAAAAyJA/L58BtmgUqxM/s800/icon_business_man12.png" width="220px" height="200px" >
		<p>名前７</p>
	</div>
	<div class="icon-face">
		<img src="https://1.bp.blogspot.com/-X47oiCDvrw4/Vf-auE06zxI/AAAAAAAAyJ0/Xyz7RgGS2yg/s800/icon_business_woman03.png" width="220px" height="200px" >
		<p>名前８</p>
	</div>
	<div class="icon-face">
		<img src="https://4.bp.blogspot.com/-07Fj2RvHvNw/Vf-am2wUVEI/AAAAAAAAyH4/wniywd4OwXM/s800/icon_business_man03.png" width="220px" height="200px" >
		<p>名前９</p>
	</div>
	<%= link_to(new_face_path, class: 'face-btn') do %>
		<span class='face-btn-text'>カオを追加</span>
		<%= image_tag 'https://1.bp.blogspot.com/-1DEjTTe66zg/WGCffbZpkRI/AAAAAAABAos/OgHE3v13Jccwenmb_uhQGuy-K74f7qo4gCLcB/s800/camera_man_boy.png' , size: '185x50' ,class: "face-btn-icon" %>
	<% end %>
	
</div>

app/views/faces/new.html.erb
<div class="faces-contents">
  <div class="faces-main">
    <h2 class="faces-title">カオの情報を入力</h2>
    <%= form_with model: @face, local: true do |f| %>

    <%# カオ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        カオの画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"faces-image" %>
      </div>
    </div>
    <%# /カオ画像 %>
    <%# 自己紹介 %>
    <div class="new-faces">
			<div class="faces-explain">
        <div class="weight-bold-text">
          自己紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"faces-text", id:"face-info", placeholder:"自己紹介（必須 500文字まで）" ,rows:"6" ,maxlength:"500" %>
      </div>
			<div class="faces-explain">
				<div class="weight-bold-text">
					スキル
					<span class="indispensable">必須</span>
				</div>
				<%= f.text_area :text, class:"faces-text", id:"face-text", placeholder:"スキル（必須 100文字まで)", maxlength:"100" %>
			</div>
      <div class="faces-explain">
        <div class="weight-bold-text">
          趣味
					<span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"faces-text", id:"face-info", placeholder:"趣味（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /自己紹介 %>

    <%# カオの詳細 %>
    <div class="faces-detail">
      <div class="weight-bold-text">カオの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"face-gender"}) %>
        <div class="weight-bold-text">
          出身地
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:birthplace_id, Birthplace.all, :id, :name, {}, {class:"select-box", id:"face-department"}) %>
				<div class="weight-bold-text">
          部署
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:department_id, Department.all, :id, :name, {}, {class:"select-box", id:"face-department"}) %>
				<div class="weight-bold-text">
					勤続年数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:history_id, History.all, :id, :name, {}, {class:"select-box", id:"face-department"}) %>
      </div>
    </div>
    <%# /カオの詳細 %>

    <%# 下部ボタン %>
    <div class="register-btn-contents">
      <%= f.submit "登録する" ,class:"register-btn" %>
      <%=link_to 'もどる', faces_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/faces/show.html.erb
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
			<% if @item.order.present? %>
				<div class="sold-out">
					<span>Sold Out!!</span>
				</div>
			<% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= "¥ #{@item.price}" %>
      </span>
      <span class="item-postage">
        <%= @item.shipping_cost.name %>
      </span>
    </div>

		<% if user_signed_in? && @item.order.nil? %>
			<% if current_user.id == @item.user_id %>
				<%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
				<p class="or-text">or</p>
				<%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
			<% else %>
				<%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-red-btn"%>
			<% end %>
		<% end %>

    <div class="item-explain-box">
      <span><%= @item.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_cost.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.delivery_time.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "tweets/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'ルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
				<select name="room[user_ids][]">
					<option value="">ユーザーを選択してください</option>
					<% User.all.where.not(id: current_user.id).each do |user| %>
						<option value=<%= user.id %>><%= user.name %></option>
					<% end %>
				</select>
				<input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/_main_chat.html.erb
<div class="chat-header">
	<div class="room-name">
		<%= @room.name %>
	</div>
	<div class="chat-end">
		<%= link_to "チャットを終了する", room_path(@room), method: :delete %>
	</div>
</div>

<div class="tweets">
	<%= render partial: 'tweet', collection: @tweets %>
</div>

<%= form_with model: [@room, @tweet], class: 'forms', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :text, class: 'form-tweet', placeholder: 'type a tweet' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/tweets/_side_bar.html.erb
<div class="side-bar-header">
	<div class="user-name">
		<%= link_to current_user.name %>
	</div>
	<div class="chat-create">
		<a href="/rooms/new">チャットを作成する</a>
	</div>
</div>

<div class="rooms">
	<% current_user.rooms.each do |room| %>
		<div class="room">
			<div class="room-name">
				<%= link_to room.name, room_tweets_path(room) %>
			</div>
		</div>
	<% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <div class="upper-tweet">
    <div class="tweet-user">
      <!-- 投稿したユーザー名情報を出力する -->
			<%= tweet.user.name %>
    </div>
    <div class="tweet-date">
      <!-- 投稿した時刻を出力する -->
			<%= l tweet.created_at %>
    </div>
  </div>
  <div class="lower-tweet">
    <div class="tweet-comment">
      <!-- 投稿したメッセージ内容を記述する -->
			<%= tweet.text %>
    </div>
		<%= image_tag tweet.image.variant(resize: '400x400'), class: 'tweet-image' if tweet.image.attached? %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
	<div class="side-bar">
		<%= render "side_bar" %>
	</div>
	<div class="main-chat">
		<%= render "main_chat" %>
	</div>
</div>